name: publish

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install pandoc
        run: |
          sudo apt-get install --no-install-recommends pandoc
        
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx
          pip install nbsphinx
          
      - name: Build Sphinx Documentation
        run: |
          cd docs_sphinx
          make html
          
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check contents
        run: |
          pwd
          ls
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: docs_sphinx/_build/html
          CLEAN: true
          SSH: true
          COMMIT_MESSAGE: "[skip ci] Deploy to GitHub Pages"
